spring:
  application:
    name: "blog"
  data:
    mongodb:
      uri: ${MONGODB_URI}
      auto-index-creation: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://idp.example.com/issuer"
server:
  port: 8081