spring:
  application:
    name: "blog"
  data:
    mongodb:
      uri: "mongodb+srv://dnsfr:P9uBehRLw0eROSul@dfrblog.kqbgs.mongodb.net/?retryWrites=true&w=majority&appName=DFRBLOG"
jwt:
  secret: "CentennialCollege"
server:
  port: 8081