import type { Metadata } from "next";
import localFont from "next/font/local";
import Link from "next/link"; // Import Link
import "./globals.css";
import "react-quill/dist/quill.snow.css";
import "react-quill/dist/quill.core.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <nav className="navbar">
        <Link href="/pages/home" style={{ textDecoration: 'none', color: 'white' }}> {/* Make logo clickable */}
          <h1>Dan's Farmaroot</h1>
        </Link>
        <ul className="nav-links">
          <li>
            <Link href="/pages/login" style={{ fontWeight: 'bold', color: 'white', textDecoration: 'none' }}>Login</Link> {/* Bold Login button */}
          </li>
        </ul>
      </nav>
      {children}
      </body>
      </html>
  );
}
